/// Flutter icons TreeTypeIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TreeTypeIcons
///      fonts:
///       - asset: fonts/TreeTypeIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TreeTypeIcons {
  TreeTypeIcons._();

  static const _kFontFam = 'TreeTypeIcons';
  static const _kFontPkg = null;

  static const IconData palm_tree = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pine = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tree_1 = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tree_17 = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
